# **04 School Matcher**

In [1]:
# Importing required packages
import os
import glob
import pandas as pd
pd.set_option('max_colwidth', 400)  #wider pandas columns upon render
import numpy as np
from itertools import islice
import thefuzz
from thefuzz import fuzz, process
from datetime import date

# Printing the working directory
os.getcwd()

'c:\\Users\\toofa\\OneDrive - Baylor College of Medicine\\APSA\\2024-07-29_Texas-STAR'

## **Replacement of fuzzy string matches**

In [ ]:
# Importing merged star programs (merged with the applicant-level data from R)
programs = pd.read_csv("tables/STAR_Programs_2017_2023_merged.csv")
programs.head()

/tmp/ipykernel_6973/640562799.py:2: DtypeWarning: Columns (6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  programs = pd.read_csv("tables/STAR_Programs_2017_2023_merged.csv")

,STAR.ID,Program.Institution,ACGME.Code,Interview.Offer,Matched,Geographic.Connection,Geographic.Preference.ERAS.Supp.App,Away.Rotation,Signaled.Program,Specialty,degrees,program_specialty
0,2017010001,Baylor College of Medicine,NaN,Y,Y,N,NaN,N,NaN,Anesthesiology,MD,Baylor College of Medicine_Anesthesiology
1,2017010001,Beth Israel Deaconess Medical Center/Harvard Medical School,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Beth Israel Deaconess Medical Center/Harvard Medical School_Anesthesiology
2,2017010001,Duke University Hospital,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Duke University Hospital_Anesthesiology
3,2017010001,Massachusetts General Hospital/Harvard Medical School,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Massachusetts General Hospital/Harvard Medical School_Anesthesiology
4,2017010001,Texas A&M College of Medicine-Scott and White,NaN,Y,N,N,NaN,N,NaN,Anesthesiology,MD,Texas A&M College of Medicine-Scott and White_Anesthesiology

In [ ]:
# Importing all the matched programs, mapping original program names to doximity names from 03_school_matcher.py
matching_docs = glob.glob("dox_matching/*.xlsx")
match_list = [pd.read_excel(x) for x in matching_docs]
match_df = pd.concat(match_list)
match_df["dox_program"] = match_df["dox_program"].replace({"USC/LAC+USC Medical Center": "University of Southern California/Los Angeles General Medical Center (USC/LA General)"})
match_df.head()

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,84.0,100.0,87.0,100.0,74.0,Baylor College of Medicine,Baylor College of Medicine (Houston),Plastic Surgery,89
1,NaN,NaN,NaN,NaN,NaN,Beaumont Health (Farmington Hills and Royal Oak),Beaumont Health (Farmington Hills and Royal Oak),Plastic Surgery,unable to match
2,76.0,100.0,76.0,100.0,78.0,Beth Israel Deaconess Medical Center,Beth Israel Deaconess Medical Center/Harvard Medical School,Plastic Surgery,86
3,83.0,100.0,83.0,100.0,85.0,Mass General Brigham/Brigham and Women's Hospital/Harvard Medical School,Brigham and Women's Hospital/Harvard Medical School,Plastic Surgery,90.2
4,42.0,100.0,43.0,100.0,81.0,Brown University,Brown University (Women and Infants Hospital of Rhode Island),Plastic Surgery,73.2

In [ ]:
# Looping through each specialty and replacing original program names with doximity program names for accurate rank list comparisons
programs_df_list = []
specialties = match_df["specialty"].sort_values().unique()  #unique specialties

for s in specialties:
    print("Matching {}".format(s))
    match_df_filt = match_df[match_df["specialty"]==s]
    programs_filt = programs[programs["Specialty"]==s].copy()
    
    # Making a replacement dictionary for each specialty
    specialty_dict = {}
    for index, row in match_df_filt.iterrows():
        dox_p = row["dox_program"]
        star_p = row["star_program"]
        specialty_dict[star_p] = dox_p
    
    # Replacing program institution names with doximity ones
    programs_filt.loc[:, "Program.Institution.Dox"] = programs_filt["Program.Institution"].replace(specialty_dict)
    programs_df_list.append(programs_filt)

# Concatenating values
programs_final = pd.concat(programs_df_list)
programs_final

Matching Anesthesiology
Matching Child Neurology
Matching Dermatology
Matching Emergency Medicine
Matching Family Medicine
Matching Internal Medicine
Matching Internal Medicine-Emergency Medicine
Matching Internal Medicine-Pediatrics
Matching Internal Medicine-Preliminary
Matching Internal Medicine-Psychiatry
Matching Neurodevelopmental Disabilities
Matching Neurological Surgery
Matching Neurology
Matching Obstetrics and Gynecology
Matching Ophthalmology
Matching Orthopaedic Surgery
Matching Osteopathic Neuromusculoskeletal Medicine
Matching Otolaryngology
Matching Pathology
Matching Pediatrics
Matching Pediatrics-Medical Genetics
Matching Pediatrics-Psychiatry-Child and Adolescent Psychiatry
Matching Physical Medicine and Rehabilitation
Matching Plastic Surgery
Matching Preventive Medicine
Matching Psychiatry
Matching Radiation Oncology
Matching Radiology-Diagnostic
Matching Radiology-Interventional
Matching Surgery
Matching Surgery-Preliminary
Matching Thoracic Surgery
Matching Transitional Year
Matching Urology
Matching Vascular Surgery

,STAR.ID,Program.Institution,ACGME.Code,Interview.Offer,Matched,Geographic.Connection,Geographic.Preference.ERAS.Supp.App,Away.Rotation,Signaled.Program,Specialty,degrees,program_specialty,Program.Institution.Dox
0,2017010001,Baylor College of Medicine,NaN,Y,Y,N,NaN,N,NaN,Anesthesiology,MD,Baylor College of Medicine_Anesthesiology,Baylor College of Medicine
1,2017010001,Beth Israel Deaconess Medical Center/Harvard Medical School,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Beth Israel Deaconess Medical Center/Harvard Medical School_Anesthesiology,Beth Israel Deaconess Medical Center
2,2017010001,Duke University Hospital,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Duke University Hospital_Anesthesiology,Duke University Hospital
3,2017010001,Massachusetts General Hospital/Harvard Medical School,NaN,N,N,N,NaN,N,NaN,Anesthesiology,MD,Massachusetts General Hospital/Harvard Medical School_Anesthesiology,Mass General Brigham/Massachusetts General Hospital
4,2017010001,Texas A&M College of Medicine-Scott and White,NaN,Y,N,N,NaN,N,NaN,Anesthesiology,MD,Texas A&M College of Medicine-Scott and White_Anesthesiology,Texas A&M College of Medicine-Scott and White Medical Center (Temple)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1634198,2023355034,USC/LAC+USC Medical Center,4.510512e+09,N,N,N,N,N,N,Vascular Surgery,MD,USC/LAC+USC Medical Center_Vascular Surgery,University of Southern California/Los Angeles General Medical Center (USC/LA General)
1634199,2023355034,Washington University/B-JH/SLCH Consortium,4.512800e+09,N,N,N,N,N,N,Vascular Surgery,MD,Washington University/B-JH/SLCH Consortium_Vascular Surgery,Washington University/B-JH/SLCH Consortium
1634200,2023355034,Yale-New Haven Medical Center,4.510821e+09,N,N,N,N,N,N,Vascular Surgery,MD,Yale-New Haven Medical Center_Vascular Surgery,Yale-New Haven Medical Center
1634201,2023355034,Zucker School of Medicine at Hofstra/Northwell,4.513500e+09,N,N,N,N,N,N,Vascular Surgery,MD,Zucker School of Medicine at Hofstra/Northwell_Vascular Surgery,Zucker School of Medicine at Hofstra/Northwell
1634202,2023355034,Zucker School of Medicine at Hofstra/Northwell at Lenox Hill Hospital,4.513512e+09,N,N,N,N,N,N,Vascular Surgery,MD,Zucker School of Medicine at Hofstra/Northwell at Lenox Hill Hospital_Vascular Surgery,Zucker School of Medicine at Hofstra/Northwell at Lenox Hill Hospital

In [ ]:
# Exporting the dataframe
#programs_final.to_csv("tables/STAR_Programs_2017_2023_final_matched.csv", index=False)

## **Fuzzy string match for inexact program matches**
#### Imported from R

#### Test code for 03_school_matcher.py

In [23]:
unmatched["specialty"].unique()

array(['Anesthesiology', 'Child Neurology', 'Dermatology',
       'Emergency Medicine', 'Family Medicine', 'Internal Medicine',
       'Internal Medicine-Emergency Medicine',
       'Internal Medicine-Pediatrics', 'Internal Medicine-Preliminary',
       'Internal Medicine-Psychiatry', 'Neurodevelopmental Disabilities',
       'Neurological Surgery', 'Neurology', 'Obstetrics and Gynecology',
       'Ophthalmology', 'Orthopaedic Surgery',
       'Osteopathic Neuromusculoskeletal Medicine', 'Otolaryngology',
       'Pathology', 'Pediatrics', 'Pediatrics-Medical Genetics',
       'Pediatrics-Psychiatry-Child and Adolescent Psychiatry',
       'Physical Medicine and Rehabilitation', 'Plastic Surgery',
       'Preventive Medicine', 'Psychiatry', 'Radiation Oncology',
       'Radiology-Diagnostic', 'Radiology-Interventional', 'Surgery',
       'Surgery-Preliminary', 'Thoracic Surgery', 'Transitional Year',
       'Urology', 'Vascular Surgery'], dtype=object)

In [21]:
star = pd.read_csv("tables/texasSTAR_unique_programs.csv")
unmatched = pd.read_csv("tables/unmatched_unique_programs.csv")
dox = pd.read_excel("tables/doximity_rankings.xlsx")  #doximity rankings
br = pd.read_excel("blueridge_data/SchoolOfMedicine_2024_2001_B.xlsx", sheet_name='2024_2001', header=1)  #blueridge data
br = br[0:157]

display(star.head())
display(unmatched.head())
display(dox.head())
display(br.head())

,star_programs,program,specialty
0,Baylor College of Medicine_Anesthesiology,Baylor College of Medicine,Anesthesiology
1,Beth Israel Deaconess Medical Center/Harvard Medical School_Anesthesiology,Beth Israel Deaconess Medical Center/Harvard Medical School,Anesthesiology
2,Duke University Hospital_Anesthesiology,Duke University Hospital,Anesthesiology
3,Massachusetts General Hospital/Harvard Medical School_Anesthesiology,Massachusetts General Hospital/Harvard Medical School,Anesthesiology
4,Texas A&M College of Medicine-Scott and White_Anesthesiology,Texas A&M College of Medicine-Scott and White,Anesthesiology

,unmatched_programs,program,specialty
0,Advocate Health Care (Advocate Illinois Masonic Medical Center)_Anesthesiology,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology
1,Baylor College of Medicine (Houston)_Anesthesiology,Baylor College of Medicine (Houston),Anesthesiology
2,Beaumont Health (Royal Oak and Taylor)_Anesthesiology,Beaumont Health (Royal Oak and Taylor),Anesthesiology
3,Beaumont Health (Royal Oak)_Anesthesiology,Beaumont Health (Royal Oak),Anesthesiology
4,Beaumont Health (Taylor)_Anesthesiology,Beaumont Health (Taylor),Anesthesiology

,program,location,program_size,rank,specialty,sort_by
0,Mass General Brigham/Massachusetts General Hospital,Boston,116,1,Anesthesiology,reputation
1,University of California (San Francisco),San Francisco,96,2,Anesthesiology,reputation
2,Stanford Health Care-Sponsored Stanford University,Stanford,108,3,Anesthesiology,reputation
3,Mass General Brigham/Brigham and Women's Hospital,Boston,128,4,Anesthesiology,reputation
4,Duke University Hospital,Durham,60,5,Anesthesiology,reputation

,No.,Name,2024,2023,2022,2021,2020,2019,2018,2017,...,2008,2007,2006,2005,2004,2003,2002,2001,Mean,Std dev
0,1.0,ALBANY MEDICAL COLLEGE,102,102,106,104.0,101.0,104,107.0,108.0,...,103.0,105,104.0,107,101,98.0,100.0,96,103.666667,3.059791
1,2.0,ALBERT EINSTEIN COLLEGE OF MEDICINE,35,35,34,35.0,30.0,34,32.0,28.0,...,31.0,32,27.0,27,20,25.0,23.0,24,28.583333,4.363053
2,3.0,AUGUSTA UNIVERSITY,64,68,74,73.0,73.0,73,73.0,67.0,...,75.0,77,75.0,78,74,75.0,80.0,78,72.666667,3.941603
3,4.0,BAYLOR COLLEGE OF MEDICINE,20,20,20,20.0,20.0,21,20.0,21.0,...,16.0,15,15.0,12,10,9.0,5.0,7,16.625000,4.688677
4,5.0,BOSTON UNIVERSITY MEDICAL CAMPUS,45,45,48,46.0,47.0,45,45.0,46.0,...,41.0,44,39.0,40,38,12.0,39.0,41,42.458333,7.138257

In [3]:
for index, row in islice(unmatched.iterrows(), 10):
    program = row["program"]
    specialty = row["specialty"]
    print(program, specialty)

Advocate Health Care (Advocate Illinois Masonic Medical Center) Anesthesiology
Baylor College of Medicine (Houston) Anesthesiology
Beaumont Health (Royal Oak and Taylor) Anesthesiology
Beaumont Health (Royal Oak) Anesthesiology
Beaumont Health (Taylor) Anesthesiology
Beth Israel Deaconess Medical Center/Harvard Medical School Anesthesiology
Brigham and Women's Hospital Anesthesiology
Brigham and Women's Hospital/Harvard Medical School Anesthesiology
Butler Hospital/Brown University Anesthesiology
Case Western Reserve University (MetroHealth) Anesthesiology

In [12]:
match_list = []
for index, row in islice(unmatched.iterrows(), 5):
    program = row["program"]
    specialty = row["specialty"]
    
    dox_filt = dox[dox["specialty"]==specialty]
    dox_filt = dox_filt["program"].unique()
    
    ratio = []
    partial_ratio = []
    sort_ratio = []
    set_ratio = []
    partial_token = []
    dox_program_list = []
    for dox_program in dox_filt:
        ratio.append(fuzz.ratio(program, dox_program))
        partial_ratio.append(fuzz.partial_ratio(program, dox_program))
        sort_ratio.append(fuzz.token_sort_ratio(program, dox_program))
        set_ratio.append(fuzz.token_set_ratio(program, dox_program))
        partial_token.append(fuzz.partial_token_sort_ratio(program, dox_program))
        dox_program_list.append(dox_program)
    
    df = pd.DataFrame({"ratio": ratio, "partial_ratio": partial_ratio, "sort_ratio": sort_ratio, "set_ratio": set_ratio, "partial_token": partial_token, "dox_program": dox_program_list})
    df["star_program"] = program
    df["specialty"] = specialty
    df["mean_ratio"] = df[["ratio", "partial_ratio", "sort_ratio", "set_ratio", "partial_token"]].mean(axis=1)
    df = df.sort_values("mean_ratio", ascending=False).reset_index(drop=True)
    display(df.head(10))
    
    selection = input("Select the top match by index: ")
    if selection=="done":
        print("finished with looping")
        break
    try:
        selection = int(selection)
        matched_df = pd.DataFrame(df.iloc[selection]).transpose()
        match_list.append(matched_df)
        display(matched_df)
    except:
        print("unable to match")
        unmatched_df = pd.DataFrame({"ratio": np.nan, "partial_ratio": np.nan, "sort_ratio": np.nan, "set_ratio": np.nan, "partial_token": np.nan, "dox_program": program, "star_program": program, "specialty": specialty, "mean_ratio": "unable to match"}, index=[0])
        match_list.append(unmatched_df)
        display(unmatched_df)

df_total = pd.concat(match_list)
display(df_total)

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,97,97,100,100,100,Advocate Health Care/Advocate Illinois Masonic Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,98.8
1,43,84,44,82,67,Maine Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,64.0
2,45,83,49,72,68,Maimonides Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,63.4
3,51,78,48,68,67,Cedars-Sinai Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,62.4
4,45,81,41,80,63,Albany Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,62.0
5,41,83,35,82,62,Tufts Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,60.6
6,59,56,49,61,60,HCA Healthcare/Los Robles Regional Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,57.0
7,45,71,39,70,58,St Joseph's Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,56.6
8,48,68,42,65,59,St Elizabeth's Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,56.4
9,55,66,49,56,55,Beth Israel Deaconess Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,56.2

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,97,97,100,100,100,Advocate Health Care/Advocate Illinois Masonic Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,98.8

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,84,100,87,100,74,Baylor College of Medicine,Baylor College of Medicine (Houston),Anesthesiology,89.0
1,64,78,54,72,72,University of Arizona College of Medicine-Tucson,Baylor College of Medicine (Houston),Anesthesiology,68.0
2,63,71,56,72,71,Mayo Clinic College of Medicine and Science (Arizona),Baylor College of Medicine (Houston),Anesthesiology,66.6
3,59,70,56,72,74,University of Illinois College of Medicine at Peoria,Baylor College of Medicine (Houston),Anesthesiology,66.2
4,64,71,55,72,68,Mayo Clinic College of Medicine and Science (Rochester),Baylor College of Medicine (Houston),Anesthesiology,66.0
5,58,69,57,72,74,University of Illinois College of Medicine at Chicago,Baylor College of Medicine (Houston),Anesthesiology,66.0
6,62,75,55,72,62,University of Florida College of Medicine Jacksonville,Baylor College of Medicine (Houston),Anesthesiology,65.2
7,62,71,58,72,62,Mayo Clinic College of Medicine and Science (Jacksonville),Baylor College of Medicine (Houston),Anesthesiology,65.0
8,56,74,55,72,68,University of Kentucky College of Medicine,Baylor College of Medicine (Houston),Anesthesiology,65.0
9,56,71,49,72,72,University of Tennessee College of Medicine,Baylor College of Medicine (Houston),Anesthesiology,64.0

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,84,100,87,100,74,Baylor College of Medicine,Baylor College of Medicine (Houston),Anesthesiology,89.0

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,51,69,67,82,72,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak and Taylor),Anesthesiology,68.2
1,32,67,42,67,75,Tower Health,Beaumont Health (Royal Oak and Taylor),Anesthesiology,56.6
2,45,60,54,54,65,AdventHealth Florida,Beaumont Health (Royal Oak and Taylor),Anesthesiology,55.6
3,44,51,53,56,57,Cook County Health and Hospitals System,Beaumont Health (Royal Oak and Taylor),Anesthesiology,52.2
4,49,56,48,51,51,McLaren Health Care/Oakland/MSU,Beaumont Health (Royal Oak and Taylor),Anesthesiology,51.0
5,35,64,32,60,57,Nuvance Health,Beaumont Health (Royal Oak and Taylor),Anesthesiology,49.6
6,41,49,49,49,54,University of Texas Health Science Center at Tyler,Beaumont Health (Royal Oak and Taylor),Anesthesiology,48.4
7,41,47,48,51,54,McLaren Health Care Corporation,Beaumont Health (Royal Oak and Taylor),Anesthesiology,48.2
8,43,45,47,51,52,Sutter Health/Sutter Roseville Medical Center,Beaumont Health (Royal Oak and Taylor),Anesthesiology,47.6
9,39,51,43,47,55,Kettering Health Network,Beaumont Health (Royal Oak and Taylor),Anesthesiology,47.0

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,51,69,67,82,72,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak and Taylor),Anesthesiology,68.2

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,59,85,78,100,87,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak),Anesthesiology,81.8
1,41,67,49,67,75,Tower Health,Beaumont Health (Royal Oak),Anesthesiology,59.8
2,51,60,58,58,63,AdventHealth Florida,Beaumont Health (Royal Oak),Anesthesiology,58.0
3,44,64,41,60,57,Nuvance Health,Beaumont Health (Royal Oak),Anesthesiology,53.2
4,48,56,50,54,56,McLaren Health Care/Oakland/MSU,Beaumont Health (Royal Oak),Anesthesiology,52.8
5,45,56,50,53,60,Cook County Health and Hospitals System,Beaumont Health (Royal Oak),Anesthesiology,52.8
6,45,51,50,50,58,McLaren Health Care Corporation,Beaumont Health (Royal Oak),Anesthesiology,50.8
7,43,56,46,45,62,Oregon Health & Science University (OHSU Health),Beaumont Health (Royal Oak),Anesthesiology,50.4
8,40,54,47,47,62,HCA HealthONE,Beaumont Health (Royal Oak),Anesthesiology,50.0
9,42,48,46,51,61,Sutter Health/Sutter Roseville Medical Center,Beaumont Health (Royal Oak),Anesthesiology,49.6

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,59,85,78,100,87,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak),Anesthesiology,81.8

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,43,64,62,81,65,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Taylor),Anesthesiology,63.0
1,59,63,62,62,67,AdventHealth Florida,Beaumont Health (Taylor),Anesthesiology,62.6
2,44,67,59,67,75,Tower Health,Beaumont Health (Taylor),Anesthesiology,62.4
3,47,64,44,60,59,Nuvance Health,Beaumont Health (Taylor),Anesthesiology,54.8
4,47,57,53,53,62,McLaren Health Care Corporation,Beaumont Health (Taylor),Anesthesiology,54.4
5,41,55,49,49,64,Cook County Health and Hospitals System,Beaumont Health (Taylor),Anesthesiology,51.6
6,38,54,51,51,62,HCA HealthONE,Beaumont Health (Taylor),Anesthesiology,51.2
7,50,55,43,57,51,Kettering Health Network,Beaumont Health (Taylor),Anesthesiology,51.2
8,47,51,49,49,54,Geisinger Health System,Beaumont Health (Taylor),Anesthesiology,50.0
9,42,58,39,44,65,Oregon Health & Science University (OHSU Health),Beaumont Health (Taylor),Anesthesiology,49.6

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,43,64,62,81,65,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Taylor),Anesthesiology,63.0

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,dox_program,star_program,specialty,mean_ratio
0,97,97,100,100,100,Advocate Health Care/Advocate Illinois Masonic Medical Center,Advocate Health Care (Advocate Illinois Masonic Medical Center),Anesthesiology,98.8
0,84,100,87,100,74,Baylor College of Medicine,Baylor College of Medicine (Houston),Anesthesiology,89.0
0,51,69,67,82,72,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak and Taylor),Anesthesiology,68.2
0,59,85,78,100,87,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Royal Oak),Anesthesiology,81.8
0,43,64,62,81,65,Corewell Health East Beaumont (Royal Oak),Beaumont Health (Taylor),Anesthesiology,63.0

In [5]:
ratio = []
for index, row in star.iterrows():
    r = fuzz.ratio(row["star_programs"], row["program"])
    ratio.append(r)
star["ratio"] = ratio
star

,star_programs,program,specialty,ratio
0,Baylor College of Medicine_Anesthesiology,Baylor College of Medicine,Anesthesiology,78
1,Beth Israel Deaconess Medical Center/Harvard Medical School_Anesthesiology,Beth Israel Deaconess Medical Center/Harvard Medical School,Anesthesiology,89
2,Duke University Hospital_Anesthesiology,Duke University Hospital,Anesthesiology,76
3,Massachusetts General Hospital/Harvard Medical School_Anesthesiology,Massachusetts General Hospital/Harvard Medical School,Anesthesiology,88
4,Texas A&M College of Medicine-Scott and White_Anesthesiology,Texas A&M College of Medicine-Scott and White,Anesthesiology,86
...,...,...,...,...
10729,Loma Linda University Health Education Consortium Public Health and General Preventive Medicine_Preventive Medicine,Loma Linda University Health Education Consortium Public Health and General Preventive Medicine,Preventive Medicine,90
10730,Texas Department of State Health Services Public Health and General Preventive Medicine_Preventive Medicine,Texas Department of State Health Services Public Health and General Preventive Medicine,Preventive Medicine,90
10731,University at Buffalo Public Health and General Preventive Medicine_Preventive Medicine,University at Buffalo Public Health and General Preventive Medicine,Preventive Medicine,87
10732,University of Texas Health Science Center at Houston Occupational Medicine_Preventive Medicine,University of Texas Health Science Center at Houston Occupational Medicine,Preventive Medicine,88
10733,Wayne State University School of Public Health and General Preventive Medicine_Preventive Medicine,Wayne State University School of Public Health and General Preventive Medicine,Preventive Medicine,89

In [ ]:
today = str(date.today())
print(today + "_Anesthiology")

2024-12-12_Anesthiology

In [22]:
# Blueridge 
br = pd.read_excel("blueridge_data/SchoolOfMedicine_2024_2001_B.xlsx", sheet_name='2024_2001', header=1)
br = br[0:157]

br["Name"].str.lower().unique()

array(['albany medical college', 'albert einstein college of medicine',
       'augusta  university', 'baylor college of medicine',
       'boston university medical campus', 'brown university',
       'case western reserve u & cleveland clinic lerner com',
       'central michigan university', 'charles r. drew univ of med & sci',
       'city college of new york', 'cleveland clinic lerner com-cwru',
       'columbia university health sciences',
       'cornell university weill medical college', 'creighton university',
       'dartmouth college', 'drexel university', 'duke university',
       'east carolina university', 'east tennessee state university',
       'eastern virginia medical school', 'emory university',
       'florida atlantic university', 'florida international university',
       'florida state university', 'george washington university',
       'georgetown university', 'harvard medical school',
       'hofstra university', 'howard university',
       'indiana university indianapolis', 'johns hopkins university',
       'loma linda university', 'louisiana state univ hsc new orleans',
       'louisiana state univ hsc shreveport', 'loyola university chicago',
       'marshall university', 'mayo clinic rochester',
       'medical college of wisconsin',
       'medical university of south carolina', 'meharry medical college',
       'mercer university macon',
       'michigan state university & henry ford health',
       'morehouse school of medicine',
       'mount sinai icahn school of medicine', 'new york medical college',
       'new york university school of medicine',
       'northeast ohio medical university',
       'northwestern university chicago', 'oakland university',
       'ohio state university', 'oklahoma state univ for health sciences',
       'oregon health & science university',
       'pennsylvania state univ med ctr hershey',
       'ponce school of medicine', 'rbhs-cancer institute of new jersey',
       'rbhs-new jersey medical school',
       'rbhs-robert wood johnson medical school',
       'rosalind franklin univ of med & sci', 'rowan university',
       'rush university medical center',
       'rutgers biomedical and health sciences',
       'rutgers, the state university of new jersey',
       'saint louis university', 'san juan bautista school of medicine',
       'southern illinois university carbondale',
       'southern illinois university springfield', 'stanford university',
       'state university of new york buffalo',
       'state university of new york stony brook',
       'suny downstate medical center', 'suny upstate medical center',
       'temple university', 'texas a&m university health science center',
       'texas tech university hsc el paso',
       'texas tech university hsc lubbock', 'thomas jefferson university',
       'touro university', 'tufts university boston', 'tulane university',
       'universidad central del caribe',
       'university of alabama birmingham',
       'university of alabama tuscaloosa',
       'university of alaska anchorage', 'university of arizona',
       'university of arkansas for med scis',
       'university of california davis',
       'university of california irvine',
       'university of california los angeles',
       'university of california riverside',
       'university of california san diego',
       'university of california san francisco',
       'university of central florida', 'university of chicago',
       'university of cincinnati', 'university of colorado denver',
       'university of connecticut sch of med/dnt',
       'university of florida', 'university of hawaii manoa',
       'university of houston', 'university of illinois chicago',
       'university of illinois urbana-champaign', 'university of iowa',
       'university of kansas medical center', 'university of kentucky',
       'university of louisville', 'university of maryland baltimore',
       'university of massachusetts med sch worcester',
       'university of miami school of medicine',
       'university of michigan ann arbor', 'university of minnesota',
       'university of minnesota duluth',
       'university of mississippi med ctr',
       'university of missouri columbia',
       'university of missouri kansas city',
       'university of nebraska medical center',
       'university of nevada las vegas', 'university of nevada reno',
       'university of new mexico hlth scis ctr',
       'university of north carolina chapel hill',
       'university of north dakota',
       'university of north texas hlth sci ctr',
       'university of oklahoma hlth scis ctr',
       'university of pennsylvania', 'university of pittsburgh',
       'university of puerto rico med scis', 'university of rochester',
       'university of south alabama',
       'university of south carolina columbia',
       'university of south dakota', 'university of south florida',
       'university of southern california',
       'university of tennessee hlth sci ctr',
       'university of tennessee knoxville', 'university of texas austin',
       'university of texas hlth sci ctr houston',
       'university of texas hlth sci ctr san antonio',
       'university of texas hlth sci ctr tyler',
       'university of texas med br galveston',
       'university of texas rio grande valley',
       'university of texas southwestern dallas',
       'university of toledo hlth sci campus', 'university of utah',
       'university of vermont', 'university of virginia',
       'university of washington seattle',
       'university of wisconsin madison', 'vanderbilt university',
       'virginia commonwealth university',
       'virginia polytechnic inst and st univ',
       'wake forest university hlth scis', 'washington state university',
       'washington university st louis', 'wayne state university',
       'west virginia university',
       'western michigan univ school of medicine',
       'wright state university', 'yale university'], dtype=object)

In [29]:
anesth = pd.read_excel("blueridge_matching/2025-12-29_anethesiology.xlsx")
anesth = anesth[anesth["mean_ratio"]!="unable to match"]
anesth

,ratio,partial_ratio,sort_ratio,set_ratio,partial_token,blueridge_program,star_program,specialty,mean_ratio
1,84.0,100.0,87.0,100.0,74.0,baylor college of medicine,baylor college of medicine (houston),Anesthesiology,89
5,54.0,100.0,54.0,100.0,82.0,harvard medical school,beth israel deaconess medical center/harvard medical school,Anesthesiology,78
6,44.0,45.0,40.0,40.0,44.0,harvard medical school,brigham and women's hospital,Anesthesiology,42.6
7,60.0,100.0,60.0,100.0,73.0,harvard medical school,brigham and women's hospital/harvard medical school,Anesthesiology,78.6
8,67.0,100.0,67.0,100.0,81.0,brown university,butler hospital/brown university,Anesthesiology,83
...,...,...,...,...,...,...,...,...,...
140,100.0,100.0,100.0,100.0,100.0,university of virginia,university of virginia,Anesthesiology,100
141,75.0,90.0,72.0,86.0,86.0,university of washington seattle,university of washington school of medicine,Anesthesiology,81.8
142,85.0,100.0,85.0,100.0,100.0,university of wisconsin madison,university of wisconsin,Anesthesiology,94
144,79.0,100.0,81.0,100.0,100.0,west virginia university,west virginia university (morgantown),Anesthesiology,92
146,NaN,NaN,NaN,NaN,NaN,hofstra university,zucker school of medicine at hofstra/northwell at cohen children's medical center,Anesthesiology,56.6

In [30]:
ex_dict = {}
for index, row in anesth.iterrows():
    star_p = row["star_program"]
    blueridge_p = row["blueridge_program"]
    ex_dict[star_p] = blueridge_p
ex_dict

{'baylor college of medicine (houston)': 'baylor college of medicine',
 'beth israel deaconess medical center/harvard medical school': 'harvard medical school',
 "brigham and women's hospital": 'harvard medical school',
 "brigham and women's hospital/harvard medical school": 'harvard medical school',
 'butler hospital/brown university': 'brown university',
 'case western reserve university (metrohealth)': 'case western reserve u & cleveland clinic lerner com',
 'case western reserve university (metrohealth)-preliminary': 'case western reserve u & cleveland clinic lerner com',
 'cleveland clinic (florida)': 'cleveland clinic lerner com-cwru',
 'dartmouth- hitchcock/mary hitchcock memorial hospital': 'dartmouth college',
 'detroit medical center/wayne state university (sinai grace)': 'wayne state university',
 'detroit medical center/wayne state university (sinai-grace)': 'wayne state university',
 'drexel university college of medicine/hahnemann university': 'drexel university',
 'drexel university college of medicine/hahnemann university hospital': 'drexel university',
 'george washington university school of medicine': 'george washington university',
 'georgetown university hospital': 'georgetown university',
 'henry ford hospital/wayne state university': 'wayne state university',
 'hofstra northwell school of medicine': 'hofstra university',
 'icahn school of medicine at mount sinai': 'mount sinai icahn school of medicine',
 "icahn school of medicine at mount sinai (st luke's-roosevelt hospital center)": 'mount sinai icahn school of medicine',
 'icahn school of medicine at mount sinai/st luke': 'mount sinai icahn school of medicine',
 "icahn school of medicine at mount sinai/st luke's-roosevelt hospital center": 'mount sinai icahn school of medicine',
 'icahn school of medicine at mount sinai/st lukes roosevelt hospital center': 'mount sinai icahn school of medicine',
 'indiana university school of medicine/methodist hospital': 'indiana university indianapolis',
 'louisiana state university (new orleans)': 'louisiana state univ hsc new orleans',
 'louisiana state university school of medicine': 'louisiana state univ hsc new orleans',
 'loyola university': 'loyola university chicago',
 'mary hitchcock memorial hospital/dartmouth-hitchcock': 'dartmouth college',
 'massachusetts general hospital': 'harvard medical school',
 'massachusetts general hospital/harvard medical school': 'harvard medical school',
 'medstar health/georgetown-washington hospital center': 'george washington university',
 'medical university of south carolina college of medicine': 'medical university of south carolina',
 'metrohealth medical center/case western reserve university': 'case western reserve u & cleveland clinic lerner com',
 'mount sinai medical center of florida': 'mount sinai icahn school of medicine',
 'mount sinai medical center of florida inc': 'mount sinai icahn school of medicine',
 'new york medical college at metropolitan hospital': 'new york medical college',
 "new york medical college at st joseph's regional medical center": 'new york medical college',
 'new york medical college at westchester medical center': 'new york medical college',
 'new york university school of medicine': 'new york university school of medicine',
 'oregon health   science university': 'oregon health & science university',
 'oregon health & science university': 'oregon health & science university',
 'oregon health & science university hospital': 'oregon health & science university',
 'penn state milton s hershey medical center/hershey': 'pennsylvania state univ med ctr hershey',
 'riverside university health system/university of california riverside': 'university of california riverside',
 'rutgers new jersey medical school': 'rbhs-new jersey medical school',
 'rutgers robert wood johnson medical school': 'rbhs-robert wood johnson medical school',
 'suny health science center at brooklyn': 'suny downstate medical center',
 'suny upstate': 'suny upstate medical center',
 'st louis university school of medicine': 'saint louis university',
 'st louis university school of medicine (saint louis)': 'saint louis university',
 'stanford health care-sponsored stanford university/kaiser permanente medical center': 'stanford university',
 'stanford university': 'stanford university',
 'stony brook medicine': 'state university of new york stony brook',
 'strong memorial hospital of the university of rochester': 'university of rochester',
 'texas a&m college of medicine-scott and white': 'texas a&m university health science center',
 'texas a&m college of medicine-scott and white medical center': 'texas a&m university health science center',
 'texas tech university (lubbock)': 'texas tech university hsc lubbock',
 'ucla medical center': 'university of california los angeles',
 'umms-baystate': 'university of massachusetts med sch worcester',
 'umass chan-baystate': 'university of massachusetts med sch worcester',
 'upmc lititz': 'university of pittsburgh',
 'upmc medical education (pittsburgh)': 'university of pittsburgh',
 'upmc pinnacle lititz': 'university of pittsburgh',
 'usc/lac+usc medical center': 'university of southern california',
 'university at buffalo school of medicine': 'state university of new york buffalo',
 'university of arizona college of medicine': 'university of arizona',
 'university of arkansas college of medicine': 'university of arkansas for med scis',
 'university of arkansas for medical sciences': 'university of arkansas for med scis',
 'university of california (san diego)': 'university of california san diego',
 'university of california (san francisco) school of medicine': 'university of california san francisco',
 'university of california (san francisco)/san francisco general hospital': 'university of california san francisco',
 'university of california irvine': 'university of california irvine',
 'university of california riverside school of medicine': 'university of california riverside',
 'university of california san diego medical center': 'university of california san diego',
 'university of california san francisco': 'university of california san francisco',
 'university of central florida/hca gme consortium': 'university of central florida',
 'university of central florida/hca gme consortium (greater orlando)': 'university of central florida',
 'university of central florida/hca gme consortium (ocala)': 'university of central florida',
 'university of central florida/hca healthcare gme (ocala)': 'university of central florida',
 'university of chicago medical center': 'university of chicago',
 'university of colorado (rural training track)': 'university of colorado denver',
 'university of colorado school of medicine': 'university of colorado denver',
 'university of florida (gainesville)': 'university of florida',
 'university of florida (jacksonville )': 'university of florida',
 'university of florida college of medicine': 'university of florida',
 'university of louisville': 'university of louisville',
 'university of maryland at mercy medical center-preliminary': 'university of maryland baltimore',
 'university of maryland/sheppard pratt': 'university of maryland baltimore',
 'university of massachusetts': 'university of massachusetts med sch worcester',
 'university of massachusetts medical school': 'university of massachusetts med sch worcester',
 'university of michigan health system': 'university of michigan ann arbor',
 'university of minnesota medical school': 'university of minnesota',
 'university of mississippi school of medicine': 'university of mississippi med ctr',
 'university of missouri at kansas city': 'university of missouri kansas city',
 'university of nebraska medical center': 'university of nebraska medical center',
 'university of new mexico': 'university of new mexico hlth scis ctr',
 'university of pennsylvania': 'university of pennsylvania',
 'university of puerto rico school of medicine': 'university of puerto rico med scis',
 'university of rochester/highland hospital of rochester': 'university of rochester',
 'university of southern california/lac+usc medical center': 'university of southern california',
 'university of tennesse college of medicine': 'university of tennessee knoxville',
 'university of texas health science center school of medicine at san antonio': 'university of texas hlth sci ctr san antonio',
 'university of texas health science center at houston (memorial hermann hospital)': 'texas a&m university health science center',
 'university of texas health science center at houston/md anderson cancer center': 'university of texas hlth sci ctr houston',
 'university of texas medical branch hospitals/methodist hospital (houston)': 'university of texas med br galveston',
 'university of texas southwestern medical school': 'university of texas southwestern dallas',
 'university of utah': 'university of utah',
 'university of utah medical center': 'university of utah',
 'university of virginia': 'university of virginia',
 'university of washington school of medicine': 'university of washington seattle',
 'university of wisconsin': 'university of wisconsin madison',
 'west virginia university (morgantown)': 'west virginia university',
 "zucker school of medicine at hofstra/northwell at cohen children's medical center": 'hofstra university'}

In [123]:
unmatched_filt = unmatched[unmatched["specialty"]=='Ophthalmology']
unmatched_filt["program"] = unmatched_filt['program'].str.lower()
print(unmatched_filt.shape)
print(len(unmatched_filt['program'].unique()))
programs = unmatched_filt['program'].unique()

(108, 3)
108

C:\Users\toofa\AppData\Local\Temp\ipykernel_57176\1604551522.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unmatched_filt["program"] = unmatched_filt['program'].str.lower()

In [124]:
programs

array(['beaumont health (royal oak and taylor)',
       'beaumont health (royal oak)', 'beaumont health (taylor)',
       'bronx-lebanon hospital center/albert einstein college of medicine',
       'brown university (women and infants hospital of rhode island)',
       'brown university/rhode island hospital-lifespan',
       'butler hospital/brown university',
       'dartmouth- hitchcock/mary hitchcock memorial hospital',
       'detroit medical center/wayne state university (sinai grace)',
       'doctors hospital/ohiohealth',
       'drexel university college of medicine/hahnemann university',
       'drexel university college of medicine/hahnemann university hospital',
       'george washington university school of medicine',
       'georgetown university hospital/washington hospital center',
       'hca healthcare/usf morsani college of medicine gme: regional medical center bayonet point',
       'hca west florida gme consortium', 'henry ford hospital',
       'henry ford hospital/wayne state university',
       'hofstra northwell school of medicine',
       'icahn school of medicine at mount sinai',
       'icahn school of medicine at mount sinai (mount sinai hospital)',
       'icahn school of medicine at mount sinai/mount sinai hospital',
       'icahn school of medicine at mount sinai/new york eye and ear infirmary at mount sinai',
       'indiana university school of medicine/methodist hospital',
       'jackson memorial hospital/jackson health system',
       'john h stroger hospital of cook county',
       'kettering health network/kettering medical center',
       'louisiana state university',
       'louisiana state university school of medicine',
       'louisiana state university school of medicine (new orleans)',
       'loyola university', 'madigan healthcare system',
       'massachusetts eye and ear infirmary/harvard medical school',
       'medstar heath/washington hospital center',
       'medical university of south carolina college of medicine',
       'methodist hospital (houston)',
       'new york university school of medicine',
       'oakwood southshore hospital',
       'oregon health & science university',
       'oregon health & science university hospital',
       'palmetto health/university of south carolina school of medicine',
       'penn state milton s hershey medical center/hershey',
       'prisma health-midlands/university of south carolina school of medicine-columbia',
       'rutgers new jersey medical school',
       'suny health science center at brooklyn',
       'sidney kimmel medical college at thomas jefferson university/wills eye institute',
       'st john macomb-oakland hospital',
       'st john macomb-oakland hospital (warren)',
       'st louis university school of medicine',
       'st louis university school of medicine (saint louis)',
       'stanford university', 'stony brook medicine',
       'strong memorial hospital of the university of rochester',
       'summa health system/neomed',
       'texas a&m college of medicine-scott and white',
       'texas a&m college of medicine-scott and white medical center',
       'texas tech university (lubbock)',
       'ucla david geffen school of medicine/ucla medical center',
       'ucla medical center', 'upmc medical education (pittsburgh)',
       'usc/lac+usc medical center',
       'university at buffalo school of medicine',
       'university of arizona college of medicine',
       'university of arizona college of medicine at south campus',
       'university of arizona college of medicine- tucson',
       'university of arizona college of medicine-tucson (south campus)',
       'university of arkansas college of medicine',
       'university of arkansas for medical sciences',
       'university of california  program - irvine',
       'university of california (san diego)',
       'university of california (san francisco) school of medicine',
       'university of california (san francisco)/san francisco general hospital',
       'university of california irvine',
       'university of california san diego medical center',
       'university of california san francisco',
       'university of chicago medical center',
       'university of colorado (rural training track)',
       'university of florida (gainesville)',
       'university of florida college of medicine',
       'university of louisville',
       'university of maryland at mercy medical center-preliminary',
       'university of maryland/sheppard pratt',
       'university of massachusetts medical school',
       'university of miami/jackson health system',
       'university of michigan health system',
       'university of minnesota medical school',
       'university of mississippi school of medicine',
       'university of missouri at kansas city',
       'university of nebraska medical center',
       'university of puerto rico school of medicine',
       'university of rochester/highland hospital of rochester',
       'university of south florida morsani college of medicine',
       'university of southern california/lac+usc medical center',
       'university of tennessee college of medicine',
       'university of tennessee college of medicine at memphis',
       'university of texas health science center school of medicine at san antonio',
       'university of texas health science center at houston (memorial hermann hospital)',
       'university of texas health science center at houston/md anderson cancer center',
       'university of texas southwestern medical school',
       'university of utah', 'university of utah medical center',
       'university of virginia',
       'university of washington school of medicine',
       'university of wisconsin',
       'wake forest university baptist medical center',
       'west virginia university school of medicine',
       'william beaumont hospital',
       "zucker school of medicine at hofstra/northwell at cohen children's medical center"],
      dtype=object)