## **Python Dictionary Storage**

In [179]:
import pickle
import pandas as pd
import glob
import re
import numpy as np

In [131]:
d1 = {
    'albert einstein healthcare network': 'albert einstein college of medicine',
    'albert einstein medical center': 'albert einstein college of medicine',
    'baylor college of medicine (houston)': 'baylor college of medicine',
    'beth israel deaconess medical center/harvard medical school': 'harvard medical school',
    'charleston area medical center/camc institute for academic medicine': 'west virginia university',
    'charleston area medical center/west virginia university (charleston division)': 'west virginia university',
    'cooper hospital-university medical center': 'cooper medical school of rowan university',
    'dartmouth- hitchcock/mary hitchcock memorial hospital': 'dartmouth college',
    'georgetown university hospital/washington hospital center': 'georgetown university',
    'grand rapids medical education partners/michigan state university': 'michigan state university & henry ford health',
    'hofstra northwell school of medicine at lenox hill hospital': 'hofstra university',
    'indiana university school of medicine/methodist hospital': 'indiana university indianapolis',
    'jackson memorial hospital/jackson health system': 'university of miami school of medicine',
    'louisiana state university': 'louisiana state univ hsc new orleans',
    'louisiana state university (new orleans)': 'louisiana state univ hsc new orleans',
    'mary hitchcock memorial hospital/dartmouth-hitchcock': 'dartmouth college',
    'massachusetts general hospital': 'harvard medical school',
    'massachusetts general hospital/harvard medical school': 'harvard medical school',
    'medical university of south carolina college of medicine': 'medical university of south carolina',
    'new york university school of medicine': 'new york university school of medicine',
    'oregon health & science university hospital': 'oregon health & science university',
    'penn state milton s hershey medical center/hershey': 'pennsylvania state university-hershey',
    'rutgers robert wood johnson medical school': 'rutgers robert wood johnson med sch',
    'southern illinois university school of medicine': 'southern illinois university',
    'spectrum health/michigan state university': 'michigan state university & henry ford health',
    'st louis university school of medicine': 'saint louis university',
    'st louis university school of medicine (saint louis)': 'saint louis university',
    'stanford health care-sponsored stanford university/kaiser permanente medical center': 'stanford university',
    'stanford university': 'stanford university',
    'stony brook medicine': 'state university of new york stony brook',
    'strong memorial hospital of the university of rochester': 'university of rochester',
    'ucla medical center': 'university of california los angeles',
    'upmc medical education (pittsburgh)': 'university of pittsburgh',
    'usc/lac+usc medical center': 'university of southern california',
    'university at buffalo school of medicine': 'state university of new york buffalo',
    'university of arizona college of medicine': 'university of arizona',
    'university of arizona college of medicine- tucson': 'university of arizona',
    'university of arkansas college of medicine': 'university of arkansas for med scis',
    'university of arkansas for medical sciences': 'university of arkansas for med scis',
    'university of california san francisco school of medicine': 'university of california san francisco',
    'university of massachusetts': 'university of massachusetts worcester',
    'university of massachusetts medical school': 'university of massachusetts worcester',
    'university of michigan health system': 'university of michigan ann arbor',
    'university of minnesota medical school': 'university of minnesota',
    'university of pennsylvania': 'university of pennsylvania',
    'university of rochester/highland hospital of rochester': 'university of rochester',
    'university of south florida morsani college of medicine': 'university of south florida',
    'university of southern california/lac+usc medical center': 'university of southern california',
    'university of texas health science center at houston (memorial hermann hospital)': 'university of texas hlth sci ctr houston',
    'university of texas medical branch hospitals/methodist hospital (houston)': 'university of texas medical branch',
    'university of washington': 'university of washington seattle',
    'university of wisconsin': 'university of wisconsin-madison'
}

In [261]:
# Saving
specialty = "Ophthalmology"
#with open("blueridge_matching/" + specialty + ".pkl", "wb") as f:
#    pickle.dump(d1, f)
    
# Reading
with open("blueridge_matching/" + specialty + ".pkl", "rb") as f:
    d_sample = pickle.load(f)
d_sample

{'beaumont health (royal oak and taylor)': 'oakland university',
 'beaumont health (royal oak)': 'oakland university',
 'beaumont health (taylor)': 'oakland university',
 'bronx-lebanon hospital center/albert einstein college of medicine': 'albert einstein college of medicine',
 'brown university (women and infants hospital of rhode island)': 'brown university',
 'brown university/rhode island hospital-lifespan': 'brown university',
 'butler hospital/brown university': 'brown university',
 'dartmouth- hitchcock/mary hitchcock memorial hospital': 'dartmouth college',
 'detroit medical center/wayne state university (sinai grace)': 'wayne state university',
 'drexel university college of medicine/hahnemann university': 'drexel university',
 'drexel university college of medicine/hahnemann university hospital': 'drexel university',
 'george washington university school of medicine': 'george washington university',
 'georgetown university hospital/washington hospital center': 'georgetown university',
 'hca healthcare/usf morsani college of medicine gme: regional medical center bayonet point': 'university of south florida',
 'hca west florida gme consortium': 'university of south florida',
 'henry ford hospital': 'michigan state university & henry ford health',
 'henry ford hospital/wayne state university': 'wayne state university',
 'hofstra northwell school of medicine': 'hofstra university',
 'icahn school of medicine at mount sinai': 'mount sinai',
 'icahn school of medicine at mount sinai (mount sinai hospital)': 'mount sinai',
 'icahn school of medicine at mount sinai/mount sinai hospital': 'mount sinai',
 'icahn school of medicine at mount sinai/new york eye and ear infirmary at mount sinai': 'mount sinai',
 'indiana university school of medicine/methodist hospital': 'indiana university indianapolis',
 'jackson memorial hospital/jackson health system': 'university of miami school of medicine',
 'louisiana state university': 'louisiana state univ hsc new orleans',
 'louisiana state university school of medicine': 'louisiana state univ hsc new orleans',
 'louisiana state university school of medicine (new orleans)': 'louisiana state univ hsc new orleans',
 'loyola university': 'loyola university chicago',
 'massachusetts eye and ear infirmary/harvard medical school': 'harvard medical school',
 'medical university of south carolina college of medicine': 'medical university of south carolina',
 'new york university school of medicine': 'new york university',
 'oregon health & science university': 'oregon health & science university',
 'oregon health & science university hospital': 'oregon health & science university',
 'palmetto health/university of south carolina school of medicine': 'university of south carolina columbia',
 'penn state milton s hershey medical center/hershey': 'pennsylvania state univ med ctr hershey',
 'prisma health-midlands/university of south carolina school of medicine-columbia': 'university of south carolina columbia',
 'rutgers new jersey medical school': 'rbhs-new jersey medical school',
 'suny health science center at brooklyn': 'state university of new york downstate',
 'sidney kimmel medical college at thomas jefferson university/wills eye institute': 'thomas jefferson university',
 'st louis university school of medicine': 'saint louis university',
 'st louis university school of medicine (saint louis)': 'saint louis university',
 'stanford university': 'stanford university',
 'stony brook medicine': 'state university of new york stony brook',
 'strong memorial hospital of the university of rochester': 'university of rochester',
 'texas a&m college of medicine-scott and white': 'texas a&m university health science center',
 'texas a&m college of medicine-scott and white medical center': 'texas a&m university health science center',
 'texas tech university (lubbock)': 'texas tech university hsc lubbock',
 'ucla david geffen school of medicine/ucla medical center': 'university of california los angeles',
 'ucla medical center': 'university of california los angeles',
 'upmc medical education (pittsburgh)': 'university of pittsburgh',
 'usc/lac+usc medical center': 'university of southern california',
 'university at buffalo school of medicine': 'state university of new york buffalo',
 'university of arizona college of medicine': 'university of arizona',
 'university of arizona college of medicine at south campus': 'university of arizona',
 'university of arizona college of medicine- tucson': 'university of arizona',
 'university of arizona college of medicine-tucson (south campus)': 'university of arizona',
 'university of arkansas college of medicine': 'university of arkansas for med scis',
 'university of arkansas for medical sciences': 'university of arkansas for med scis',
 'university of california program - irvine': 'university of california irvine',
 'university of california (san diego)': 'university of california san diego',
 'university of california (san francisco) school of medicine': 'university of california san francisco',
 'university of california (san francisco)/san francisco general hospital': 'university of california san francisco',
 'university of california irvine': 'university of california irvine',
 'university of california san diego medical center': 'university of california san diego',
 'university of california san francisco': 'university of california san francisco',
 'university of chicago medical center': 'university of chicago',
 'university of colorado (rural training track)': 'university of colorado denver',
 'university of florida (gainesville)': 'university of florida',
 'university of florida college of medicine': 'university of florida',
 'university of louisville': 'university of louisville',
 'university of maryland at mercy medical center-preliminary': 'university of maryland baltimore',
 'university of massachusetts medical school': 'university of massachusetts med sch worcester',
 'university of miami/jackson health system': 'university of miami school of medicine',
 'university of michigan health system': 'university of michigan ann arbor',
 'university of minnesota medical school': 'university of minnesota',
 'university of mississippi school of medicine': 'university of mississippi med ctr',
 'university of missouri at kansas city': 'university of missouri-kansas city',
 'university of nebraska medical center': 'university of nebraska medical center',
 'university of puerto rico school of medicine': 'university of puerto rico med scis',
 'university of rochester/highland hospital of rochester': 'university of rochester',
 'university of south florida morsani college of medicine': 'university of south florida',
 'university of southern california/lac+usc medical center': 'university of southern california',
 'university of tennessee college of medicine': 'university of tennessee hlth sci ctr',
 'university of tennessee college of medicine at memphis': 'university of tennessee hlth sci ctr',
 'university of texas health science center school of medicine at san antonio': 'university of texas hlth sci ctr san antonio',
 'university of texas health science center at houston (memorial hermann hospital)': 'university of texas hlth sci ctr houston',
 'university of texas health science center at houston/md anderson cancer center': 'university of texas hlth sci ctr houston',
 'university of texas southwestern medical school': 'university of texas southwestern dallas',
 'university of utah': 'university of utah',
 'university of utah medical center': 'university of utah',
 'university of virginia': 'university of virginia',
 'university of washington school of medicine': 'university of washington seattle',
 'university of wisconsin': 'university of wisconsin madison',
 'wake forest university baptist medical center': 'wake forest university hlth scis',
 'west virginia university school of medicine': 'west virginia university',
 'william beaumont hospital': 'oakland university',
 "zucker school of medicine at hofstra/northwell at cohen children's medical center": 'hofstra university'}

In [133]:
print(len(d1))
print(len(d_sample))

52
52

In [264]:

# Merging all ranks
pickle_list = glob.glob("blueridge_matching/*.pkl")

df_list = []
for pick in pickle_list:
    with open(pick, "rb") as f:
        temp_dict = pickle.load(f)
    df = pd.DataFrame(list(temp_dict.items()), columns=["star_program", "blueridge_program"])
    specialty = re.findall(r'\\(.*?)\.pkl', pick)[0]
    print(specialty)
    df["specialty"] = specialty
    df_list.append(df)
blueridge_ranks = pd.concat(df_list, ignore_index=True) 
blueridge_ranks

Anesthesiology
Child Neurology
Dermatology
Emergency Medicine
Family Medicine
Internal Medicine-Emergency Medicine
Internal Medicine-Pediatrics
Internal Medicine-Preliminary
Internal Medicine-Psychiatry
Internal Medicine
Neurodevelopmental Disabilities
Neurological Surgery
Neurology
Obstetrics and Gynecology
Ophthalmology
Orthopaedic Surgery
Osteopathic Neuromusculoskeletal Medicine
Otolaryngology
Pathology
Pediatrics-Medical Genetics
Pediatrics-Psychiatry-Child and Adolescent Psychiatry
Pediatrics
Physical Medicine and Rehabilitation
Plastic Surgery
Preventive Medicine
Psychiatry
Radiation Oncology
Radiology-Diagnostic
Radiology-Interventional
Surgery-Preliminary
Surgery
Thoracic Surgery
Transitional Year
Urology
Vascular Surgery

,star_program,blueridge_program,specialty
0,baylor college of medicine (houston),baylor college of medicine,Anesthesiology
1,beaumont health (royal oak and taylor),oakland university,Anesthesiology
2,beaumont health (royal oak),oakland university,Anesthesiology
3,beaumont health (taylor),oakland university,Anesthesiology
4,beth israel deaconess medical center/harvard m...,harvard medical school,Anesthesiology
...,...,...,...
4228,university of southern california/lac+usc medi...,university of southern california,Vascular Surgery
4229,university of texas health science center at h...,university of texas hlth sci ctr houston,Vascular Surgery
4230,university of texas medical branch hospitals/m...,university of texas medical branch,Vascular Surgery
4231,university of washington,university of washington seattle,Vascular Surgery
4232,university of wisconsin,university of wisconsin-madison,Vascular Surgery

In [265]:
blueridge_ranks[blueridge_ranks["specialty"]=="Ophthalmology"]

,star_program,blueridge_program,specialty
2295,beaumont health (royal oak and taylor),oakland university,Ophthalmology
2296,beaumont health (royal oak),oakland university,Ophthalmology
2297,beaumont health (taylor),oakland university,Ophthalmology
2298,bronx-lebanon hospital center/albert einstein ...,albert einstein college of medicine,Ophthalmology
2299,brown university (women and infants hospital o...,brown university,Ophthalmology
...,...,...,...
2387,university of wisconsin,university of wisconsin madison,Ophthalmology
2388,wake forest university baptist medical center,wake forest university hlth scis,Ophthalmology
2389,west virginia university school of medicine,west virginia university,Ophthalmology
2390,william beaumont hospital,oakland university,Ophthalmology
2391,zucker school of medicine at hofstra/northwell...,hofstra university,Ophthalmology

In [266]:
blueridge_ranks["specialty"].unique()

array(['Anesthesiology', 'Child Neurology', 'Dermatology',
       'Emergency Medicine', 'Family Medicine',
       'Internal Medicine-Emergency Medicine',
       'Internal Medicine-Pediatrics', 'Internal Medicine-Preliminary',
       'Internal Medicine-Psychiatry', 'Internal Medicine',
       'Neurodevelopmental Disabilities', 'Neurological Surgery',
       'Neurology', 'Obstetrics and Gynecology', 'Ophthalmology',
       'Orthopaedic Surgery', 'Osteopathic Neuromusculoskeletal Medicine',
       'Otolaryngology', 'Pathology', 'Pediatrics-Medical Genetics',
       'Pediatrics-Psychiatry-Child and Adolescent Psychiatry',
       'Pediatrics', 'Physical Medicine and Rehabilitation',
       'Plastic Surgery', 'Preventive Medicine', 'Psychiatry',
       'Radiation Oncology', 'Radiology-Diagnostic',
       'Radiology-Interventional', 'Surgery-Preliminary', 'Surgery',
       'Thoracic Surgery', 'Transitional Year', 'Urology',
       'Vascular Surgery'], dtype=object)

In [ ]:
# Exporting to excel
blueridge_ranks.to_excel("blueridge_data/blueridge_TexasSTAR_program_matching.xlsx", index=False)

## Overall rankings

In [156]:
# Importing blueridge overall rankings
br = pd.read_excel("blueridge_data/SchoolOfMedicine_2024_2001_B.xlsx", sheet_name='2024_2001', header=1)
br = br[0:157]
br["Name"] = br["Name"].str.lower().unique()
cols = [2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001]
br[cols] = br[cols].apply(pd.to_numeric, errors="coerce")
br["mean_rank"] = br[[2023, 2022, 2021, 2020, 2019, 2018, 2017]].mean(axis=1, skipna=True)
br = br.drop(columns = "No.").sort_values(by="mean_rank").reset_index(drop=True)
br

,Name,2024,2023,2022,2021,2020,2019,2018,2017,2016,...,2007,2006,2005,2004,2003,2002,2001,Mean,Std dev,mean_rank
0,university of california san francisco,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,...,2.0,4.0,3.0,4.0,4.0,4.0,3.0,1.916667,1.138904,1.142857
1,johns hopkins university,6.0,5.0,4.0,5.0,3.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.083333,1.471960,3.285714
2,washington university st louis,2.0,2.0,3.0,4.0,8.0,4.0,4.0,4.0,5.0,...,5.0,5.0,4.0,3.0,2.0,3.0,4.0,4.041667,1.301476,4.142857
3,university of pennsylvania,4.0,3.0,5.0,6.0,6.0,3.0,5.0,5.0,3.0,...,3.0,3.0,2.0,2.0,3.0,2.0,2.0,3.416667,1.176460,4.714286
4,stanford university,7.0,6.0,2.0,7.0,7.0,5.0,3.0,3.0,4.0,...,13.0,9.0,11.0,9.0,11.0,12.0,11.0,8.083333,3.855168,4.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,oakland university,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147.000000,NaN,NaN
153,san juan bautista school of medicine,117.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.500000,8.893818,NaN
154,touro university,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.800000,1.643168,NaN
155,university of houston,142.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.000000,NaN,NaN
156,university of tennessee knoxville,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.000000,NaN,NaN

In [ ]:
#br.to_excel("blueridge_data/blueridge_overall_rankings.xlsx", index=False)

In [ ]:
# Importing blueridge specialty-specific rankings
br_2023 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2023_B.xlsx", sheet_name='2023', header=1)

In [224]:
def br_importer(df, year):
    """
    Function to import and clean blueridge specialty-specific rankings
    Args:
        df (dataframe)
        year (int)
    """
    df.columns = df.columns.str.title()
    df["Organization Name"] = df["Organization Name"].str.lower() 
    df = df.dropna(subset=["Rank"])
    cols = ["Organization Name", "Anesthesiology", "Dermatology", 'Emergency Medicine', 'Family Medicine', 'Genetics', 'Internal Medicine/Medicine', 'Neurology', 'Neurosurgery', 'Obstetrics & Gynecology', 'Ophthalmology', 'Orthopedics', 'Otolaryngology', 'Pathology', 'Pediatrics', 'Physical Medicine & Rehab', 'Psychiatry', 'Public Health & Prev Medicine', 'Radiation-Diagnostic/Oncology', "Surgery", "Urology"]
    df = df[cols]
    specialties = [c for c in cols if c != "Organization Name"]
    df = df.melt(id_vars=["Organization Name"], value_vars=specialties, var_name="specialty", value_name="blueridge_money")
    renamed_specialties = {"Genetics": "Pediatrics-Medical Genetics", 'Internal Medicine/Medicine': "Internal Medicine", "Neurosurgery": "Neurological Surgery", "Obstetrics & Gynecology": "Obstetrics and Gynecology", "Orthopedics": "Orthopaedic Surgery", "Physical Medicine & Rehab": "Physical Medicine and Rehabilitation", "Public Health & Prev Medicine": "Preventive Medicine", "Radiation-Diagnostic/Oncology": 'Radiation Oncology'}  #not for radiation-diagnostic and oncology!!!
    df["specialty"] = df["specialty"].replace(renamed_specialties)

    br_list = []
    for spec in df["specialty"].unique():
        br_temp = df[df["specialty"]==spec].copy()
        br_temp = br_temp.dropna(subset=["blueridge_money"])
        br_temp = br_temp.sort_values(by="blueridge_money", ascending=False).reset_index(drop=True)
        br_temp["blueridge_rank"] = np.arange(1, len(br_temp)+1)
        br_temp["year"] = year
        br_list.append(br_temp)
    df = pd.concat(br_list, ignore_index=True)
    return df

In [225]:
# Importing all blueridge specialty rankings from 2020-2023
br_2023 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2023_B.xlsx", sheet_name='2023', header=1)
br_2022 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2022.xls", sheet_name='2022', header=1)
br_2021 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2021.xls", sheet_name='2021', header=1)
br_2020 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2020.xls", sheet_name='2020', header=1)

# Cleaning data
br_2023 = br_importer(br_2023, 2023)
br_2022 = br_importer(br_2022, 2022)
br_2021 = br_importer(br_2021, 2021)
br_2020 = br_importer(br_2020, 2020)
br_2020

,Organization Name,specialty,blueridge_money,blueridge_rank,year
0,university of michigan ann arbor,Anesthesiology,21454704.0,1,2020
1,washington university st louis,Anesthesiology,16192892.0,2,2020
2,stanford university,Anesthesiology,14624733.0,3,2020
3,johns hopkins university,Anesthesiology,10828478.0,4,2020
4,duke university,Anesthesiology,9226779.0,5,2020
...,...,...,...,...,...
1201,baylor college of medicine,Urology,350262.0,33,2020
1202,upstate medical university,Urology,311850.0,34,2020
1203,indiana univ-purdue univ indianapolis,Urology,311086.0,35,2020
1204,wayne state university,Urology,258812.0,36,2020
1205,university of florida,Urology,249017.0,37,2020

In [226]:
def br_importer(df, year):
    """
    Function to import and clean blueridge specialty-specific rankings - they got rid of otolaryngology in 2019 and prior :(
    Args:
        df (dataframe)
        year (int)
    """
    df.columns = df.columns.str.title()
    df["Organization Name"] = df["Organization Name"].str.lower() 
    df = df.dropna(subset=["Rank"])
    cols = ["Organization Name", "Anesthesiology", "Dermatology", 'Emergency Medicine', 'Family Medicine', 'Genetics', 'Internal Medicine/Medicine', 'Neurology', 'Neurosurgery', 'Obstetrics & Gynecology', 'Ophthalmology', 'Orthopedics', 'Pathology', 'Pediatrics', 'Physical Medicine & Rehab', 'Psychiatry', 'Public Health & Prev Medicine', 'Radiation-Diagnostic/Oncology', "Surgery", "Urology"]
    df = df[cols]
    specialties = [c for c in cols if c != "Organization Name"]
    df = df.melt(id_vars=["Organization Name"], value_vars=specialties, var_name="specialty", value_name="blueridge_money")
    renamed_specialties = {"Genetics": "Pediatrics-Medical Genetics", 'Internal Medicine/Medicine': "Internal Medicine", "Neurosurgery": "Neurological Surgery", "Obstetrics & Gynecology": "Obstetrics and Gynecology", "Orthopedics": "Orthopaedic Surgery", "Physical Medicine & Rehab": "Physical Medicine and Rehabilitation", "Public Health & Prev Medicine": "Preventive Medicine", "Radiation-Diagnostic/Oncology": 'Radiation Oncology'}  #not for radiation-diagnostic and oncology!!!
    df["specialty"] = df["specialty"].replace(renamed_specialties)

    br_list = []
    for spec in df["specialty"].unique():
        br_temp = df[df["specialty"]==spec].copy()
        br_temp = br_temp.dropna(subset=["blueridge_money"])
        br_temp = br_temp.sort_values(by="blueridge_money", ascending=False).reset_index(drop=True)
        br_temp["blueridge_rank"] = np.arange(1, len(br_temp)+1)
        br_temp["year"] = year
        br_list.append(br_temp)
    df = pd.concat(br_list, ignore_index=True)
    return df

In [227]:
# Importing all blueridge specialty rankings from 2017-2019
br_2019 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2019.xls", sheet_name='2019', header=1)
br_2018 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2018.xls", sheet_name='2018', header=1)
br_2017 = pd.read_excel("blueridge_data/MedicalSchoolsAndTheirDepartments_2017.xls", sheet_name='2017', header=1)

# Cleaning data
br_2019 = br_importer(br_2019, 2019)
br_2018 = br_importer(br_2018, 2018)
br_2017 = br_importer(br_2017, 2017)
br_2017

,Organization Name,specialty,blueridge_money,blueridge_rank,year
0,university of michigan,Anesthesiology,17066102.0,1,2017
1,washington university,Anesthesiology,12709795.0,2,2017
2,stanford university,Anesthesiology,8453246.0,3,2017
3,state university new york stony brook,Anesthesiology,8233910.0,4,2017
4,"university of california, san francisco",Anesthesiology,7333610.0,5,2017
...,...,...,...,...,...
1112,icahn school of medicine at mount sinai,Urology,260257.0,32,2017
1113,university of toledo health sci campus,Urology,200318.0,33,2017
1114,weill medical coll of cornell univ,Urology,172908.0,34,2017
1115,university of florida,Urology,120018.0,35,2017
1116,thomas jefferson university,Urology,45245.0,36,2017

In [242]:
# Standardizing all school names
standardization_map = {
    'case western reserve univ/cleveland clinic lerner com': 'case western reserve u & cleveland clinic lerner com',
    'indiana univ-purdue univ indianapolis': 'indiana university indianapolis',
    'tulane university of louisiana': 'tulane university',
    'rosalind franklin univ of medicine & sci': 'rosalind franklin univ of med & sci',
    'case western reserve u/cleveland clinic lerner com': 'case western reserve u & cleveland clinic lerner com',
    'university of massachusetts worcester': 'university of massachusetts med sch worcester',
    'university of michigan': 'university of michigan ann arbor',
    'university of washington': 'university of washington seattle',
    'university of pittsburgh at pittsburgh': 'university of pittsburgh',
    'weill medical coll of cornell univ': 'cornell university weill medical college',
    'wake forest university health sciences': 'wake forest university hlth scis',
    'rutgers, the state univ of new jersey': 'rutgers, the state university of new jersey',
    'pennsylvania state univ hershey med ctr': 'pennsylvania state univ med ctr hershey',
    'university of new mexico health sciences ctr': 'university of new mexico hlth scis ctr',
    'univ of north carolina chapel hill': 'university of north carolina chapel hill',
    'case western reserve univ/cleveland clinic lerner': 'case western reserve u & cleveland clinic lerner com',
    'icahn school of medicine at mount sinai': 'mount sinai icahn school of medicine',
    'univ of massachusetts med sch worcester': 'university of massachusetts med sch worcester',
    'university of oklahoma hlth sciences ctr': 'university of oklahoma hlth scis ctr',
    'university of arkansas for medical sciences': 'university of arkansas for med scis',
    'charles r. drew university of med & sci': 'charles r. drew univ of med & sci',
    'university of tennessee health sci ctr': 'university of tennessee hlth sci ctr',
    'texas a&m university health science ctr': 'texas a&m university health science center',
    'university of puerto rico medical sciences': 'university of puerto rico med scis',
    'upstate medical university': 'suny upstate medical center',
    'oklahoma state university ctr hlth sci': 'oklahoma state univ for health sciences',
    'texas tech university health sciences center': 'texas tech university hsc lubbock',
    'university of toledo health science campus': 'university of toledo hlth sci campus',
    'weill medical college of cornell university': 'cornell university weill medical college',
    'icahn school of medicine mount sinai': 'mount sinai icahn school of medicine',
    'oklahoma state university ctr health sci': 'oklahoma state univ for health sciences',
    'university of michigan at ann arbor': 'university of michigan ann arbor',
    'washington university': 'washington university st louis',
    'university of california, san francisco': 'university of california san francisco',
    'university of california-irvine': 'university of california irvine',
    'university of california, san diego': 'university of california san diego',
    'university of alabama at birmingham': 'university of alabama birmingham',
    'northwestern university at chicago': 'northwestern university chicago',
    'indiana univ-purdue univ at indianapolis': 'indiana university indianapolis',
    'university of wisconsin-madison': 'university of wisconsin madison',
    'state university new york stony brook': 'state university of new york stony brook',
    'university of illinois at chicago': 'university of illinois chicago',
    'university of california at davis': 'university of california davis',
    'state university of new york at buffalo': 'state university of new york buffalo',
    'temple univ of the commonwealth': 'temple university',
    'university of new mexico health scis ctr': 'university of new mexico hlth scis ctr',
    'university of vermont & st agric college': 'university of vermont',
    'university of hawaii at manoa': 'university of hawaii manoa',
    'university of missouri-columbia': 'university of missouri columbia',
    'univ of arkansas for med scis': 'university of arkansas for med scis',
    'university of puerto rico med sciences': 'university of puerto rico med scis',
    'university of toledo health sci campus': 'university of toledo hlth sci campus',
    'texas tech university health scis center': 'texas tech university hsc lubbock',
    'university of texas, austin': 'university of texas austin',
    'southern illinois university sch of med': 'southern illinois university springfield',
    'university of south carolina at columbia': 'university of south carolina columbia',
    'ut southwestern medical center': 'university of texas southwestern dallas',
    'case western reserve university': 'case western reserve u & cleveland clinic lerner com',
    'lsu health sciences center': 'louisiana state univ hsc new orleans',
    'albert einstein college of medicine, inc': 'albert einstein college of medicine',
    'lsu health sciences center new orleans': 'louisiana state univ hsc new orleans',
    'university of texas hsc san antonio': 'university of texas hlth sci ctr san antonio'
}

In [248]:
# Merging all years
br_merge = pd.concat([br_2023, br_2022, br_2021, br_2020, br_2019, br_2018, br_2017], ignore_index=True)
br_merge["Organization Name"] = br_merge["Organization Name"].replace(standardization_map)
br_merge

,Organization Name,specialty,blueridge_money,blueridge_rank,year
0,stanford university,Anesthesiology,25359262.0,1,2023
1,washington university st louis,Anesthesiology,23775845.0,2,2023
2,duke university,Anesthesiology,18165424.0,3,2023
3,wake forest university hlth scis,Anesthesiology,11803750.0,4,2023
4,vanderbilt university,Anesthesiology,11721520.0,5,2023
...,...,...,...,...,...
8214,mount sinai icahn school of medicine,Urology,260257.0,32,2017
8215,university of toledo hlth sci campus,Urology,200318.0,33,2017
8216,cornell university weill medical college,Urology,172908.0,34,2017
8217,university of florida,Urology,120018.0,35,2017
8218,thomas jefferson university,Urology,45245.0,36,2017

In [244]:
len(br_merge["Organization Name"].unique())

135

In [245]:
br_merge["Organization Name"].unique()

array(['stanford university', 'washington university st louis',
       'duke university', 'wake forest university hlth scis',
       'vanderbilt university', 'columbia university health sciences',
       'university of washington seattle',
       'university of michigan ann arbor',
       'university of california los angeles',
       'university of maryland baltimore',
       'university of california san francisco',
       'johns hopkins university',
       'university of texas hlth sci ctr houston',
       'university of pennsylvania', 'university of pittsburgh',
       'new york university school of medicine',
       'university of alabama birmingham',
       'university of kansas medical center',
       'oregon health & science university',
       'cornell university weill medical college',
       'state university of new york stony brook',
       'university of texas med br galveston',
       'rutgers, the state university of new jersey',
       'university of colorado denver', 'university of wisconsin madison',
       'university of california san diego', 'university of virginia',
       'university of rochester', 'university of nebraska medical center',
       'medical college of wisconsin', 'university of illinois chicago',
       'pennsylvania state univ med ctr hershey', 'university of chicago',
       'case western reserve u & cleveland clinic lerner com',
       'george washington university', 'university of cincinnati',
       'university of texas southwestern dallas',
       'northwestern university chicago',
       'university of miami school of medicine', 'university of utah',
       'yale university', 'university of minnesota', 'university of iowa',
       'university of california irvine', 'university of florida',
       'state university of new york buffalo', 'emory university',
       'ohio state university', 'medical university of south carolina',
       'indiana university indianapolis',
       'albert einstein college of medicine',
       'university of north carolina chapel hill',
       'mount sinai icahn school of medicine',
       'baylor college of medicine', 'boston university medical campus',
       'university of massachusetts med sch worcester',
       'university of california davis',
       'university of southern california', 'thomas jefferson university',
       'wayne state university', 'rowan university', 'temple university',
       'university of mississippi med ctr',
       'virginia commonwealth university', 'university of arizona',
       'university of oklahoma hlth scis ctr', 'university of kentucky',
       'saint louis university', 'university of hawaii manoa',
       'charles r. drew univ of med & sci',
       'university of toledo hlth sci campus',
       'university of new mexico hlth scis ctr',
       'university of arkansas for med scis', 'michigan state university',
       'dartmouth college', 'university of missouri columbia',
       'harvard medical school',
       'university of texas hlth sci ctr san antonio',
       'university of connecticut sch of med/dnt',
       'university of tennessee hlth sci ctr',
       'texas a&m university health science center',
       'louisiana state univ hsc new orleans',
       'florida international university', 'university of south florida',
       'tulane university', 'georgetown university',
       'rush university medical center', 'university of louisville',
       'augusta university', 'west virginia university',
       'morehouse school of medicine', 'university of vermont',
       'university of puerto rico med scis', 'loma linda university',
       'florida state university', 'brown university',
       'suny upstate medical center', 'loyola university chicago',
       'suny downstate medical center',
       'texas tech university hsc lubbock',
       'oklahoma state univ for health sciences',
       'meharry medical college', 'tufts university boston',
       'east carolina university', 'washington state university',
       'university of central florida', 'east tennessee state university',
       'howard university', 'drexel university',
       'university of missouri kansas city',
       'louisiana state univ hsc shreveport',
       'university of texas austin', 'creighton university',
       'rosalind franklin univ of med & sci',
       'university of south carolina columbia',
       'eastern virginia medical school', 'university of north dakota',
       'new york medical college', 'university of south alabama',
       'northeast ohio medical university',
       'university of texas rio grande valley',
       'university of nevada reno', 'albany medical college',
       'university of california riverside',
       'southern illinois university springfield',
       'wright state university', 'central michigan university',
       'university of south dakota', 'university of alabama tuscaloosa',
       'ponce school of medicine',
       'rutgers biomedical and health sciences',
       'university of tx md anderson can ctr',
       'rbhs-new jersey medical school',
       'rbhs-robert wood johnson medical school',
       'cleveland clinic lerner com-cwru'], dtype=object)

In [250]:
# Averaging ranks across years
br_avg = (
    br_merge
    .groupby(["Organization Name", "specialty"], as_index=False)
    .agg(
        mean_rank=("blueridge_rank", "mean"),
        mean_funding=("blueridge_money", "mean")
    )
    .sort_values(["specialty", "mean_rank"])
    .reset_index(drop=True)
)
br_avg

,Organization Name,specialty,mean_rank,mean_funding
0,university of michigan ann arbor,Anesthesiology,2.000000,1.921074e+07
1,washington university st louis,Anesthesiology,2.428571,1.670291e+07
2,stanford university,Anesthesiology,5.285714,1.241484e+07
3,johns hopkins university,Anesthesiology,5.428571,1.030687e+07
4,duke university,Anesthesiology,7.000000,1.034027e+07
...,...,...,...,...
1428,louisiana state univ hsc new orleans,Urology,32.000000,3.542425e+05
1429,thomas jefferson university,Urology,33.000000,4.607533e+04
1430,university of toledo hlth sci campus,Urology,33.000000,2.003180e+05
1431,wayne state university,Urology,35.000000,1.603743e+05
1432,university of florida,Urology,35.666667,1.890593e+05

In [247]:
br_avg[br_avg["specialty"]=="Ophthalmology"]

                          Organization Name      specialty  blueridge_rank
572                johns hopkins university  Ophthalmology        1.714286
573       university of southern california  Ophthalmology        2.142857
574  university of california san francisco  Ophthalmology        4.000000
575                   vanderbilt university  Ophthalmology        5.571429
576                     stanford university  Ophthalmology        7.142857
..                                      ...            ...             ...
640                university of cincinnati  Ophthalmology       62.666667
641                  saint louis university  Ophthalmology       63.333333
642                   georgetown university  Ophthalmology       63.600000
643                  university of kentucky  Ophthalmology       63.750000
644    louisiana state univ hsc new orleans  Ophthalmology       64.200000

[73 rows x 3 columns]

In [189]:
br_2023["specialty"].unique()

array(['Anesthesiology', 'Dermatology', 'Emergency Medicine',
       'Family Medicine', 'Pediatrics-Medical Genetics',
       'Internal Medicine', 'Neurology', 'Neurological Surgery',
       'Obstetrics and Gynecology', 'Ophthalmology',
       'Orthopaedic Surgery', 'Otolaryngology', 'Pathology', 'Pediatrics',
       'Physical Medicine and Rehabilitation', 'Psychiatry',
       'Preventive Medicine', 'Radiation Oncology', 'Surgery', 'Urology'],
      dtype=object)

In [168]:
br_2023.columns

Index(['Rank', 'Organization Name', 'Total Awards', 'Administration',
       'Anatomy/Cell Biology', 'Anesthesiology', 'Biochemistry', 'Biology',
       'Biomedical Engineering', 'Biophysics',
       'Biostatistics & Other Math Sci', 'Dentistry', 'Dermatology',
       'Emergency Medicine', 'Engineering (All Types)', 'Family Medicine',
       'Genetics', 'Internal Medicine/Medicine', 'Microbiology/Immun/Virology',
       'Miscellaneous', 'Neurology', 'Neurosciences', 'Neurosurgery', 'None',
       'Nutrition', 'Obstetrics & Gynecology', 'Ophthalmology', 'Orthopedics',
       'Other Basic Sciences', 'Other Clinical Sciences',
       'Other Health Professions', 'Otolaryngology', 'Pathology', 'Pediatrics',
       'Pharmacology', 'Physical Medicine & Rehab', 'Physics', 'Physiology',
       'Psychiatry', 'Psychology', 'Public Health & Prev Medicine',
       'Radiation-Diagnostic/Oncology', 'Social Sciences', 'Surgery',
       'Urology', 'Veterinary Sciences'],
      dtype='object')

In [ ]:
# Saving to excel
#br_avg.to_excel("blueridge_data/blueridge_specialty_rankings_2017-2023.xlsx", index=False)